import { describe, expect, it } from "vite-plus/test";

import golden from "./fixtures/golden-packets.json" with { type: "json" };
import {
  canonicalJson,
  PacketV1Error,
  packetV1Digest,
  parsePacketV1Text,
  sha256Hex,
  verifyPacketV1,
  verifyPacketV1Images,
} from "./packetV1.ts";

const webSha = async (value: string | Uint8Array) =>
  Array.from(
    new Uint8Array(
      await crypto.subtle.digest(
        "SHA-256",
        typeof value === "string" ? new TextEncoder().encode(value) : Uint8Array.from(value),
      ),
    ),
    (byte) => byte.toString(16).padStart(2, "0"),
  ).join("");
const download = (name: keyof typeof golden.packets) =>
  JSON.parse(golden.packets[name]) as Record<string, unknown>;
const split = (name: keyof typeof golden.packets) => {
  const { attachmentData, ...packet } = download(name);
  return {
    packet,
    attachmentData: attachmentData as { id: string; dataUrl: string }[] | undefined,
  };
};
const reason = (run: () => unknown) => {
  try {
    run();
  } catch (cause) {
    if (cause instanceof PacketV1Error) return cause.reason;
    throw cause;
  }
  return "passed";
};

describe("packet v1 port", () => {
  it("hashes like FIPS 180-4 and WebCrypto at block boundaries", async () => {
    expect(sha256Hex("")).toBe("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
    expect(sha256Hex("abc")).toBe(
      "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
    );
    for (const length of [1, 55, 56, 57, 63, 64, 65, 119, 120, 128, 1000]) {
      const bytes = Uint8Array.from({ length }, (_, index) => (index * 31 + length) & 255);
      expect(sha256Hex(bytes)).toBe(await webSha(bytes));
    }
    expect(sha256Hex("Ünïcødé · 设计 · 🎨")).toBe(await webSha("Ünïcødé · 设计 · 🎨"));
  });

  it("serializes canonical JSON like the gallery", () => {
    expect(canonicalJson({ b: 1, a: [true, null, "x", { d: 0.74, c: -2 }] })).toBe(
      '{"a":[true,null,"x",{"c":-2,"d":0.74}],"b":1}',
    );
    expect(() => canonicalJson({ a: Number.NaN })).toThrow(PacketV1Error);
    expect(() => canonicalJson(new Date(0))).toThrow(PacketV1Error);
  });

  it(`verifies golden packets generated by Frontend ${golden.sourceCommit.slice(0, 7)} byte for byte`, () => {
    expect(golden.sourceCommit).toBe("d7be667ebad2fa314a905038252e2b44954281f6");
    for (const name of ["withImages", "noImages"] as const) {
      const text = golden.packets[name];
      const { packet, attachmentData } = parsePacketV1Text(text);
      expect(packet.digest).toBe(download(name).digest);
      const { digest: _digest, ...body } = packet;
      expect(packetV1Digest(body)).toBe(packet.digest);
      // The downloaded file is the gallery's canonical serialization.
      expect(canonicalJson({ ...packet, ...(attachmentData ? { attachmentData } : {}) })).toBe(
        text,
      );
      const images = verifyPacketV1Images(packet, attachmentData);
      expect(images.map((image) => image.bytes)).toEqual(
        packet.request.attachments.map((image) => image.bytes),
      );
    }
  });

  it("rejects tampered, extended and incomplete packets before anything is sent", () => {
    const { packet, attachmentData } = split("withImages");
    const request = packet.request as Record<string, unknown>;
    expect(
      reason(() => verifyPacketV1({ ...packet, request: { ...request, note: "Edited." } })),
    ).toBe("digest-mismatch");
    expect(reason(() => verifyPacketV1({ ...packet, route: "thread-1" }))).toBe("packet-invalid");
    expect(reason(() => verifyPacketV1({ ...packet, version: 2 }))).toBe("packet-invalid");
    const verified = verifyPacketV1(packet);
    expect(reason(() => verifyPacketV1Images(verified, undefined))).toBe("attachment-mismatch");
    expect(reason(() => verifyPacketV1Images(verified, attachmentData!.slice(1)))).toBe(
      "attachment-mismatch",
    );
    const [first, second] = attachmentData!;
    const swapped = [{ id: first!.id, dataUrl: second!.dataUrl }, second!];
    expect(reason(() => verifyPacketV1Images(verified, swapped))).toBe("attachment-mismatch");
    const jpeg = [
      { id: first!.id, dataUrl: first!.dataUrl.replace("image/png", "image/jpeg") },
      second!,
    ];
    expect(reason(() => verifyPacketV1Images(verified, jpeg))).toBe("attachment-mismatch");
  });

  it("parses the copied Markdown form without images", () => {
    const { packet } = split("withImages");
    const copied = [
      "# Design request packet",
      "",
      "> note",
      "",
      "```json",
      canonicalJson(packet),
      "```",
      "",
    ].join("\n");
    const parsed = parsePacketV1Text(copied);
    expect(parsed.packet.packetId).toBe(packet.packetId);
    expect(parsed.attachmentData).toBeUndefined();
    expect(reason(() => parsePacketV1Text("not a packet"))).toBe("packet-invalid");
  });
});
